### ISSUE TITLE
Causing rails to stop working

### ISSUE THREAD

**Issue by jmcmains** [secondrotation/channel_advisor#10]
after I added this gem I received the following error when trying to run the console:

/usr/local/rvm/gems/ruby-2.1.4@rails4/gems/soap4r-1.5.8/lib/xsd/charset.rb:13: warning: variable $KCODE is no longer effective
/usr/local/rvm/gems/ruby-2.1.4@rails4/gems/soap4r-1.5.8/lib/xsd/xmlparser.rb:74:in `<top (required)>': XML processor module not found. (RuntimeError)
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/soap4r-1.5.8/lib/soap/parser.rb:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/soap4r-1.5.8/lib/xsd/mapping.rb:9:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/channel_advisor-0.2.0/lib/channel_advisor/shared_requires.rb:4:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/channel_advisor-0.2.0/lib/channel_advisor.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `each'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:72:in `block in require'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `each'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler/runtime.rb:61:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@global/gems/bundler-1.7.4/lib/bundler.rb:133:in `require'
        from /home/ubuntu/workspace/config/application.rb:7:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:82:in `require'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:82:in `preload'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:140:in `serve'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:128:in `block in run'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:122:in `loop'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application.rb:122:in `run'
        from /usr/local/rvm/gems/ruby-2.1.4@rails4/gems/spring-1.1.3/lib/spring/application/boot.rb:18:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-2.1.4/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from -e:1:in `<main>'

**Comment by ktshannon** [comment]
There seems to be an issue with running soap4r, having same problem and unfortunately can't use this gem

**Comment by ktshannon** [comment]
Had this same issue, fixed it by forking this repo and making changes to the soap4r gem to the newer version. https://github.com/ktshannon/channel_advisor/commit/b91471852ae4882c4fbd819867cd133c044e3e65

**Comment by blatyo** [comment]
My recommendation would be not to use this gem. The only thing it does is generate classes from the SOAP API channel advisor provides. It does not use the newest channel advisor API. The app that we have that uses this is still 1.9, which is probably why we haven't seen this issue ourselves.

My recommendation would be to wrap the API yourself using [savon](http://savonrb.com/).

**Comment by ktshannon** [comment]
@blatyo Agreed. This is the outdated and less stable version. I know of the one gem using Savon is https://github.com/dnunez24/channeladvisor but it's not complete, do you know of any others?

**Comment by blatyo** [comment]
I don't. Sorry.
